### PR TITLE
[macOS] Fix macOS 11 Big Sur Compatibility

### PR DESCRIPTION
**Pull request by 2a5A1Ghu1**
Screen Shot 2020-11-16 at 10 50 18 PM

### CODE REVIEW

**Comment by Willy7882** [comment]
Weet niet hoe het op te lossen

**Comment by 2a5A1Ghu1** [comment]
> Weet niet hoe het op te lossen

This fixes the issue

**Comment by 2a5A1Ghu1** [comment]
Can confirm that this commit works using rosetta on the apple m1 processor macos 11

**Comment by tohsnoom** [comment]
These changes were included in PR #84.

**Pull request closed without merging**
