### PR TITLE
Updated from PIVX v3.1.1

### PR DESCRIPTION
**Pull request by wqking**
Since Vitae version was on version 4, we may need to use new version instead of v3.1.1 for the upstream update.

### CODE REVIEW

**Comment by 2a5A1Ghu1** [comment]
I will check this and https://github.com/VitaeTeam/Vitae/pull/48 soon.

**Comment by 2a5A1Ghu1** [comment]
This bombs when building on macOS 10.15.3

`Generated test/data/sighash.json.h
Generated test/data/alertTests.raw.h
  CXX      test/test_vitae-zerocoin_implementation_tests.o
test/zerocoin_implementation_tests.cpp:486:5: error: unknown type name 'CzPIVWallet'; did you mean 'CzVITWallet'?
    CzPIVWallet zWallet(wallet.strWalletFile);
    ^~~~~~~~~~~
    CzVITWallet
./zvitwallet.h:16:7: note: 'CzVITWallet' declared here
class CzVITWallet
      ^
1 error generated.
make[2]: *** [test/test_vitae-zerocoin_implementation_tests.o] Error 1`

[config.log](https://github.com/VitaeTeam/Vitae/files/4399691/config.log)

**Comment by wqking** [comment]
If you need me to check the compile issue, let me know, otherwise I will leave it to you since you are already working it.
I disabled test in compiling to speeding up the compile speed, so the tests may be broken.

**Comment by 2a5A1Ghu1** [comment]
> If you need me to check the compile issue, let me know, otherwise I will leave it to you since you are already working it.
> I disabled test in compiling to speeding up the compile speed, so the tests may be broken.

Ok this branch fixes the compile issues I encountered.
https://github.com/VitaeTeam/Vitae/tree/pr/49

Also please do not do pull requests to our master branch :)

**Comment by wqking** [comment]
I commited a fix to this PR. Now it can compile successfully.
This PR is to a new branch, not master.

**Comment by 2a5A1Ghu1** [comment]
I did a pull request that fixes another issue to your branch so you can check it. The request not to do requests to our master was in general even though this one is a request to master https://github.com/VitaeTeam/Vitae/pull/48

**Pull request merged**
